# Generated by Django 5.1.4 on 2025-01-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BsDatapoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('ddate', models.IntegerField(blank=True, null=True)),
                ('qtrs', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=49, null=True)),
                ('report', models.IntegerField(blank=True, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('plabel', models.CharField(blank=True, max_length=1020, null=True)),
                ('negating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bs_datapoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfDatapoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('ddate', models.IntegerField(blank=True, null=True)),
                ('qtrs', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=49, null=True)),
                ('report', models.IntegerField(blank=True, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('plabel', models.CharField(blank=True, max_length=1020, null=True)),
                ('negating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cf_datapoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filings',
            fields=[
                ('adsh', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('filed', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsDatapoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('ddate', models.IntegerField(blank=True, null=True)),
                ('qtrs', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=49, null=True)),
                ('report', models.IntegerField(blank=True, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('plabel', models.CharField(blank=True, max_length=1020, null=True)),
                ('negating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'is_datapoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('cik', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_title', models.CharField(max_length=64)),
                ('stock_subtitle', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
